Cookie compliance
wearefuturegov/scout-x pull request #22
Opened 2022-02-09 20:05 UTC by apricot13

Added cookies for bod, bucks and the generic theme

Without cookies maps and auto complete do not load. It degrades 'gracefully' - map is blank autocomplete does nothing.

![image](https://user-images.githubusercontent.com/649148/153281305-a52e2057-a3cd-4fc1-afd6-4b90465896af.png)

2022-02-28 14:15 UTC, em-cd requested changes
Just a couple of small changes then this is good to go on staging for testing! 🙏

2022-02-28 14:15 UTC, em-cd commented on src/contexts/googleContext.js
> +  cookiesAccepted ? (value.isLoaded = isLoaded) : (value.isLoaded = false)
This looks a bit complicated, can we simplify it a bit? e.g.
```
<GoogleContext.Provider value={{ isLoaded: cookiesAccepted && isLoaded }} ...>
```

2022-02-28 14:15 UTC, em-cd commented on src/themes/generic/vars_generic.jsx
> +        We use cookies to collect informationabout how you use the
```suggestion
        We use cookies to collect information about how you use the
```

2022-03-04 11:54 UTC, apricot13 commented
am merging since tests are failing regardless!

2022-03-04 11:54 UTC, merged